build-cpp-tester:
	g++ -std=c++11 -L../librperf2-cpp -L../processor-trace/install/lib64 -lipt -lrperf2-cpp -I ../librperf2-cpp tester.cpp -o tester_o0
	g++ -std=c++11 -L../librperf2-cpp -L../processor-trace/install/lib64 -lipt -lrperf2-cpp -I ../librperf2-cpp -O3 tester.cpp -o tester_o3
